const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const ROOT=path.resolve(__dirname,'..');
const load=()=>import('../scripts/prepare-pages.mjs');
async function fixture(){const {RUNTIME}=await load();const dir=await fs.mkdtemp(path.join(os.tmpdir(),'luma-pages-'));for(const name of [...RUNTIME,'release.json']){await fs.mkdir(path.dirname(path.join(dir,name)),{recursive:true});await fs.copyFile(path.join(ROOT,name),path.join(dir,name));}return dir;}
test('Release catalog validates every runtime file, relative manifest and correct version',async()=>{const {validate,VERSION}=await load();const r=await validate(ROOT);assert.equal(r.version,VERSION);assert.equal(Object.keys(r.files).length,13);});
test('Pages artifact contains index.html at top level, with no duplicate docs or repository files',async()=>{const dir=await fixture();try{const {prepare}=await load();await fs.writeFile(path.join(dir,'README.md'),'not a website file');await fs.mkdir(path.join(dir,'docs'));await fs.writeFile(path.join(dir,'docs','index.html'),'old version');const result=await prepare(dir);assert.equal(result.files,14);const html=await fs.readFile(path.join(result.path,'index.html'),'utf8');assert(html.includes('name="app-version" content="4.1.0"'));await assert.rejects(fs.stat(path.join(result.path,'docs')));await assert.rejects(fs.stat(path.join(result.path,'README.md')));assert((await fs.readFile(path.join(result.path,'release.json'),'utf8')).includes('4.1.0'));}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('An empty checkout fails early with an actionable message',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'luma-empty-'));try{const{prepare}=await load();await assert.rejects(prepare(dir),/release.json ontbreekt/);}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('Missing app files and mixed versions cannot produce a new Pages artifact',async()=>{const dir=await fixture();try{const{validate}=await load();await fs.rm(path.join(dir,'assets','app.js'));await assert.rejects(validate(dir),/Ontbrekend bestand: assets\/app.js/);await fs.writeFile(path.join(dir,'assets','app.js'),'old version');await assert.rejects(validate(dir),/Niet de juiste versie/);}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('Real workflow path, minimum Pages permissions, official static upload and no Jekyll',async()=>{const yaml=await fs.readFile(path.join(ROOT,'.github','workflows','pages.yml'),'utf8');assert(yaml.includes('branches: [main]'));assert(yaml.includes('workflow_dispatch:'));assert(yaml.includes('contents: read'));assert(yaml.includes('pages: write'));assert(yaml.includes('id-token: write'));assert(yaml.includes('actions/configure-pages@v5'));assert(yaml.includes('actions/upload-pages-artifact@v4'));assert(yaml.includes('actions/deploy-pages@v4'));assert(yaml.includes('path: _site'));assert(!yaml.includes('jekyll-build'));assert(!yaml.includes('source: docs'));});
