const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const ROOT=path.resolve(__dirname,'..'),E=require('../assets/engine.js'),A=require('../assets/studio-art.js');
const old={};vm.runInNewContext(fs.readFileSync(path.join(ROOT,'assets/app.js'),'utf8').split('/* Original procedural score.')[0],old);
test('New engine preserves all 72 original campaign layouts byte-for-byte',()=>{for(let i=0;i<72;i++)assert.equal(JSON.stringify(E.generate(i)),JSON.stringify(old.LumaEngine.generate(i)));});
test('677 campaign, free-play and daily puzzles solve without changing topology',()=>{let n=0;const check=l=>{assert(E.evaluate(l,Array(l.n*l.n).fill(0)).won);assert(!E.evaluate(l,l.initial).won);n++;};for(let i=0;i<72;i++)check(E.generate(i));for(let w=0;w<6;w++)for(let n=3;n<=6;n++)for(let seed=1;seed<=10;seed++)check(E.generate(w*12+5,{world:w,n,seed:72580+seed}));for(let i=0;i<365;i++)check(E.daily(new Date(Date.UTC(2026,0,1+i)).toISOString().slice(0,10)));assert.equal(n,677);});
test('All worlds use opaque own flat landscapes, without characters or raster backgrounds',()=>{assert.equal(A.worlds.length,6);for(let w=0;w<6;w++){const s=A.scenery(w);assert(s.includes('M0 0h640v280H0Z'));assert(!/opacity=|linearGradient|<image|filter=|mask=|friend-|mascot/.test(s));}assert.equal(new Set(A.worlds.map(w=>w.accent)).size,6);});
test('Runtime excludes old mascots, rail inlays and textured styling',()=>{const html=fs.readFileSync(path.join(ROOT,'index.html'),'utf8'),css=fs.readFileSync(path.join(ROOT,'assets/studio.css'),'utf8'),js=fs.readFileSync(path.join(ROOT,'assets/studio.js'),'utf8');assert(!/worlds\.js|assets\/app\./.test(html));assert(!/pipe-inlay|pipe-shimmer|LumaWorlds|friend-face/.test(js));assert(css.includes('stroke-opacity:1'));assert(!/linear-gradient|paper.png/.test(css));assert(!/[\p{Extended_Pictographic}\uFE0F\u20E3]/u.test(html+css+js));});
test('Every connection mask has one opaque path and stays within its own cell',()=>{for(let mask=1;mask<16;mask++){const d=A.pipe(mask);assert(d.startsWith('M'));assert(!d.includes('undefined'));}const css=fs.readFileSync(path.join(ROOT,'assets/studio.css'),'utf8');assert(/\.pipe-clip\{[^}]*overflow:hidden/.test(css));assert(/\.pipe path\{[^}]*opacity:1/.test(css));});
test('PNG app icons are opaque RGB, correct size, and use the new brand',()=>{for(const n of [180,192,512]){const b=fs.readFileSync(path.join(ROOT,'icons/studio-'+n+'.png'));assert.equal(b.readUInt32BE(16),n);assert.equal(b.readUInt32BE(20),n);assert.equal(b[25],2);}const svg=fs.readFileSync(path.join(ROOT,'icons/studio.svg'),'utf8');assert(svg.includes('#CC5A43'));assert(!svg.includes('face'));});
